// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction';
import Hero from './Hero';
import Image from './Image';
import ImageCards from './ImageCards';
import NavigationItem from './NavigationItem';
import Quote from './Quote';
import Text from './Text';
import TextWithImage from './TextWithImage';

export {
	CallToAction,
	Hero,
	Image,
	ImageCards,
	NavigationItem,
	Quote,
	Text,
	TextWithImage,
};

export const components = {
	call_to_action: CallToAction,
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	navigation_item: NavigationItem,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage,
};
